---
${id!""}
${httpMethod!""}
${path!""}
${basePath!""}
${queryString!""}
${remoteAddr!""}
${remoteHost!""}
${remoteUser!""}
${userName!""}
${userRole!""}
${userGroups!""}
${host!""}
${bodyAsString!""}
${errorMessage!""}
${failed!""}
${responseStatus!""}
${responseContentType!""}
${responseLength!""}
${startTime!""}
${endTime!""}
${totalTime!""}
---
